site_title: OKA UKDW 2021
site_subtitle: Ready For A New Future With Integrity, Creativity and Compassion
site_copyright: Universitas Kristen Duta Wacana
site_date: 23 - 27 Agustus 2021
theme: Travelify
rewrite_url: true
